# Generated by Django 3.1.10 on 2023-09-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden en que se muestran')),
                ('active', models.BooleanField(default=True, verbose_name='Mostrar producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(default=0, verbose_name='Inicio')),
                ('entrada', models.IntegerField(default=0, verbose_name='Entrada')),
                ('final', models.IntegerField(default=0, verbose_name='Final')),
                ('venta', models.IntegerField(default=0, verbose_name='Venta')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe')),
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.producto', verbose_name='Producto(s)')),
            ],
            options={
                'verbose_name': 'Vendido',
                'verbose_name_plural': 'Vendidos',
                'db_table': 'vendido',
                'ordering': ['id'],
            },
        ),
    ]
