# Generated by Django 3.1.10 on 2023-09-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='entrada',
            field=models.IntegerField(default=0, verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='producto',
            name='final',
            field=models.IntegerField(default=0, verbose_name='Final'),
        ),
        migrations.AddField(
            model_name='producto',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Importe'),
        ),
        migrations.AddField(
            model_name='producto',
            name='inicio',
            field=models.IntegerField(default=0, verbose_name='Inicio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='venta',
            field=models.IntegerField(default=0, verbose_name='Venta'),
        ),
        migrations.DeleteModel(
            name='Vendido',
        ),
    ]
